spring:
  graphql:

    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /api/graphql

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
